### PR TITLE
Fix php82 access private protected prop

### PR DESCRIPTION
**Pull request by toanhminh0412**
This MR makes a frequently publicly accessed class attribute public instead of protected

### CODE REVIEW

**Comment by nkissebe** [comment]
I need to review this one. I believe the proper fix will be fix all the instances of this being accessed directly, just need to see how painful that fix would be.

**Comment by nkissebe** [comment]
Yeah this needs to be fixed caller side.  $view->task  should be changed to $view->get('task') to be consistent with intended design (good or bad).

**Comment by toanhminh0412** [comment]
Sure, I want to know what the fix it, too. Because this does seem a bit unlegit

**Comment by nkissebe** [comment]
Ok. Well I don't like it, but for now I think we have to go with this. In fact you need change all the protected attributes to be public in class View. And make a @TODO note that these should someday be changed to protected when all references have been fixed to use get()/set().  I don't understand why this worked in PHP 5.6 (and I think 7.4) or exactly what changed.

**Comment by toanhminh0412** [comment]
I converted all protected attributes to public and added a todo tag

**Pull request merged**
