### PR TITLE
Removing deprecated code

### PR DESCRIPTION
**Pull request by denphi**
This code is deprecated , http://worldcatlibraries.org is not longer available

### CODE REVIEW

**Comment by nkissebe** [comment]
If you want the code left in and commented out (as you have it now) please add a comment block describing what the commented out code does and why it is commented out.

**Comment by denphi** [comment]
Personally, I would like it to be removed. Every request to https://help.hubzero.org/citations/browse?search=test takes 10 seconds requesting an URL that no longer exists. I believe the original purpose was to load a standard XML file to format the output results, but that file no longer exists. I’m not sure if anyone in the community wants to revive that part of the code, but as I said, I would like it removed.

**Comment by nkissebe** [comment]
Either way is fine with me. Either remove it entirely. Or leave it commented out with a comment explaining why it is commented out so that if anyone goes in looking at the code they know why there is a block commented out.

**Comment by denphi** [comment]
Ok, I just removed commented out code.

**Review by nkissebe — APPROVED** [review]

**Pull request merged**
