### PR TITLE
auth_factor google auth

### PR DESCRIPTION
**Pull request by erichhuebner**

### CODE REVIEW

**Comment by hubzero-admin** [comment]
@erichhuebner will install, reference Sonata code.

**Comment by erichhuebner** [comment]
The Sonata code can't be installed and referenced directly.   A number of modifications were necessary to downgrade the code to PHP 5.6 to work in our infrastructure.  

Testing and ready to deploy for a pending deadline.

**Comment by datafatmunger** [comment]
License file needed ... then go!

**Comment by jeffkayser** [comment]
@erichhuebner to fix a bug with the table being empty after first setup.

**Pull request merged**
