### PR TITLE
Further code updates for PHP8 (created when updating the code to PHP8 for an active hub)

### PR DESCRIPTION
**Pull request by toanhminh0412**
### Summary
This MR contains changes that I made to update the code to PHP 8.2 for our hub at https://hsscommons.ca. 

### About our system
Here are the versions of the technologies that our hub is running on:
- AlmaLinux 8
- PHP 8.2
- MariaDB 10.4.34

### The process
Here is a short description of the process that I ran through to make these changes.

Our hub runs on branch `2.4-main` of the hubzero-cms code, with the `app` directory replaced with our own `app` directory. So all of our customizations are made within the `app` directory. To look for PHP 8 issues, I visited all pages that I could find on the hub, and made changes based on the error message displayed on each page. If a page had an error, I'd make the change in our `app` directory first, then made that same change in the `core` directory. For errors that weren't in the `app` directory, I'd make the change directly to the `core` directory.

All tests were manual - I made the change and refreshed the corresponding page to see if the functionality worked as expected.

### Further package updates:
There were 2 `composer` packages that I had to fork and applied custom changes as I couldn't find an official version that worked. Those two were:
- `willdurant/geocoder`: https://gitlab.com/uvic-arcsoft/etcl/php-8.2-packages/willdurand-geocoder
- `swfitmailer/swfitmailer`: https://gitlab.com/uvic-arcsoft/etcl/php-8.2-packages/swiftmailer

### Our intention
Our hub will probably still run fine without this PR being merged, though if merged, it would make our life a bit easier. These are general changes that I think will be beneficial to all hubs using the hubzero-cms. Therefore, I'm opening this PR to help you guys with your PHP8 updates in return for your kind assistance for us to update our hub.

Feel free to comment, request changes and reach out if necessary. We welcome your feedbacks!

### CODE REVIEW

**Comment by nkissebe** [comment]
Thanks a lot for the PR, it will be a very helpful reference with our next round of 8.x core updates. I won't be able to merge as-is as it is too large and varied in it's content. For instance when possible the fixes should be made 5.6 compatible, when not possible the commit needs to be label as 8.x specific (they'll get more testing if I can backport them to 2.2 branch) . The config and app directories need to remain tracked for now (although I see why you wouldn't for your environment, for us we track individual app components in seperate repos). I saw some other changes that would need independent discussion to verify the need/reason for changes. If you wanted to be involved (so that you can keep your core and our core in sync you could break this into multiple PRs by some theme (by component, by type of fix, etc) but I appreciate the effort regardless and will manually apply each commit as appropriate if you don't wish to expend the effort.

**Comment by nkissebe** [comment]
Also of note the 2.4-main branch is not a continuous update branch.  I will probably rebase it against the current dev branch before I start working through these commits.

**Comment by toanhminh0412** [comment]
Hi Nick, I'm happy to further contribute on this. Please let me know what the next step is.

Based on your comment, seems like I should open another PR that contains only updates to deprecation code, and some other PRs to deal with other types of fixes. For the PR that updates the code to PHP 8.2, my commit messages need to follow a certain format? Please confirm and further explain if needed

**Comment by nkissebe** [comment]
I'd make a PR for all the commits that are protecting against null parameters and rewrite the fixes to be PHP 5.6 compliant. (not using the null coalescing operators '??'). Also removing the first line "fix deprecated code" from the commit message and leaving it with what you are actually  fixing. And try to limit commits to be related/repeated fixes (some had null parameter fixes and regex fixes mixed together). It just makes it easier to view the commit history and selectively accept commits or assign people to review the changes. I'll do that work eventually, but I'd like retain your credit on the commits so if you do it that becomes a little easier. I really appreciate the work, we are overdue to get upgraded to PHP 8 but hadn't had the time to do the manual testing you did to uncover the null argument issues in particular which don't come up easily in static analysis scans.

**Comment by toanhminh0412** [comment]
For sure, I can start with those

**Comment by toanhminh0412** [comment]
Following up on our discussion, I created this MR: https://github.com/hubzero/hubzero-cms/pull/1741

**Comment by nkissebe** [comment]
Are you going to break out any more of these commits to PRs or should I take over?

**Comment by toanhminh0412** [comment]
Hi Nick, I'll break out the rest of the commits.

Sorry, for some reasons, I was under the impression that you were only interested in the null param ones

**Comment by nkissebe** [comment]
We'll give them all a shot. But some may require discussion/modification and thats easier with them seperated into related chunks.

**Comment by toanhminh0412** [comment]
Gotcha, I broke all commits from this PR to the followings:
- #1746
- #1747 
- #1748 
- #1749 
- #1751 
- #1752 
- #1753 
- #1754 
- #1755 

Please have a look, feel free to request changes if needed

**Comment by nkissebe** [comment]
Is there anything more in this PR that can/needs to be broken out?  When you are done with it I can review the commits and confirm we got everything and close this PR.

**Comment by toanhminh0412** [comment]
No, nothing else need to be broken out that I'm aware of

**Comment by nkissebe** [comment]
These changes exist in this PR but not your breakouts 

core/composer.json -- htmlpurifier update 
core/plugins/members/collections/collections.php -- id "" to null check
core/plugins/projects/links/helpers/simple_html_dom.php -- regex fix

**Comment by nkissebe** [comment]
I'll take the /.gitignore  change as well. That config directory shouldn't be getting created and thats a bug. But might as well exclude it from git just in case.

**Comment by nkissebe** [comment]
The app directory removal commit can't be done yet. The directories need to be there and I don't yet have an alternate means to create them. The .gitignore should have sufficient rules to make them not get in the way but if they cause you problems maybe we can come up with a solution.

**Comment by toanhminh0412** [comment]
I created:
* #1758 
* #1759 
* #1760 
* #1761 
respectively

**Comment by nkissebe** [comment]
If you want to tackle something new. swiftmailer needs to be replaced with symfony/mailer and the Hubzero mailer class refactored to use it (shouldn't be difficult. they are written by same person just refactored a bit). Also need to remove mail transport from the hubzero mailer class and get the sendmail transport to work instead. mail transport has security issues which is why support for it was removed from swiftmailer.

I thought I had transitioned geocoder to the latest version, perhaps I never committed it. I'll try to track that down. I'll send you an email direct as I am going to close this PR.

**Comment by nkissebe** [comment]
These commits have all been merged by the broken out PRs.

**Pull request closed without merging**
