### PR TITLE
[refactor] Standardize app initialization for Cli

### PR DESCRIPTION
**Pull request by zooley**
This removes the usage of the core/bootstrap/cli/shim.php file for the
command-line utility and standardizes on the core/bootstrap/start.php
file all other client types use. This keeps all client initialization
consistent.

Note: This is dependent on the referenced Framework change

Refs: https://github.com/hubzero/framework/pull/602

### CODE REVIEW

**Comment by erichhuebner** [comment]
Minor path constant updates and removal of old "TODO" code that makes more sense in the framework library.

**Comment by datafatmunger** [comment]
@erichhuebner has graciously offered to test this on a dev box somewhere.

**Comment by erichhuebner** [comment]
Tested and verified working.

**Comment by jeffkayser** [comment]
@erichhuebner to see about resolving merge conflict and/or modernizing base.

**Comment by damionjunk** [comment]
@erichhuebner see above and we'll consider for next time.

**Comment by zooley** [comment]
Due to the number of changes since this PR was made, I'm closing it in favor of this one:

https://github.com/hubzero/hubzero-cms/pull/1459

**Pull request closed without merging**
