### PR TITLE
Updated Mygroupsmini

### PR DESCRIPTION
**Pull request by BharathR8**
Styled the group logos and included a default logo for groups with no logos.

### CODE REVIEW

**Comment by zweidner** [comment]
Was this PR meant to be against qubeshub/hubzero-cms?

**Comment by BharathR8** [comment]
Sorry. It was made accidentally. You can go ahead and close it. Apologies
for the inconvenience.

Regards,
Bharath Chandra Reddy Barakam

**Comment by zweidner** [comment]
No worries, wanted to make sure it got to the right place before I spent quite awhile reviewing changes :laughing:

**Comment by BharathR8** [comment]
Thanks!

**Pull request closed without merging**
