### PR TITLE
Migrate in framework

### PR DESCRIPTION
**Pull request by erichhuebner**

### CODE REVIEW

**Comment by hubzero-admin** [comment]
What is the motivation for pulling the framework into the CMS?

**Comment by nkissebe** [comment]
It serves no purpose being separated and complicates deployment for no net benefit.

**Comment by erichhuebner** [comment]
Tested on multiple hosts and works well.  
Travis check failures are expected due to format of some template files.
Good to deploy to non-prod hosts for final testing.

**Comment by datafatmunger** [comment]
Gonna wait for a bit more testing...

**Comment by erichhuebner** [comment]
More testing completed.  No issues found.

**Pull request merged**
